### DISCUSSION TITLE
How do I have account specific SSH grunt IAM roles?

### DISCUSSION THREAD

**Discussion by yorinasub17** [gruntwork-io/knowledge-base#164] [Help] [answered]
I’m currently working with something that looks like this in `security/_global/account-baseline/users.yml`:

```
userwithlowaccess:
  create_access_keys: false
  create_login_profile: true
  groups:
  - _account.dev-full-access
  - _account.logs-read-only
  - _account.shared-read-only
  - _account.prod-read-only
  - _account.stage-read-only
  - ssh-grunt-sudo-users
```

The problem I’m running into is that `ssh-grunt-sudo-users` is creating ssh+sudo-able accounts across the whole environment.
The state I’m trying to get to would look (theoreticaly) something like this instead:

```
...
  groups:
  - _account.dev-full-access
  - _account.logs-read-only
  - _account.shared-read-only
  - _account.prod-read-only
  - _account.stage-read-only
  - _account.dev-ssh-grunt-sudo-users
```
  
(User has ssh+sudo only in a specified tenancy/role)

What’s the correct way to get there?
