### DISCUSSION TITLE
Hard limit of 10 groups per user in AWS

### DISCUSSION THREAD

**Discussion by rhoboat** [gruntwork-io/knowledge-base#188] [Help]
cross-account-iam-roles creates IAM Groups in the master account, which need to be assigned to users as required. Since most devs will need ssh-grunt-sudo-users, ssh-grunt-users, plus _account.<name>-dev, _account.<name>-openvpn-users & _account.<name>-openvpn-admins for every child account, this runs into the hard limit of 10 groups per user with more than 2 child accounts.  What is the best way of handling permissions in this case? How can this scale to larger numbers of child accounts?

**Comment by rhoboat** [comment]
You want to create dedicated cross account groups that group multiple cross account access into one group. This can be done by modifying your [cross_account_groups.yml](https://github.com/gruntwork-io/terraform-aws-service-catalog/blob/master/examples/for-production/infrastructure-live/security/_global/account-baseline/cross_account_groups.yml), which we've linked to an example of here.

For example, here is a modified version of that that will create a special group that grants access to openvpn access to all accounts:

```yaml
cross_account_groups:
  - group_name: "_account.all-openvpn"
    iam_role_arns:
#%{~ for name, id in account_ids }
      - "arn:aws:iam::${id}:role/openvpn-allow-certificate-revocations-for-external-accounts"
#%{ endfor ~}
```

This way, you only need to assign a handful of groups to the users instead of packing the user with all the individual, fine grained groups

_credit @yorinasub17_
