### DISCUSSION TITLE
How to deploy multiple containers on ECS?

### DISCUSSION THREAD

**Discussion by gruntwork-support** [gruntwork-io/knowledge-base#27] [Help] [answered]
_This message was extracted from a discussion that originally took place in Gruntwork Community Slack. Names and URLs have been removed where appropriate_

**From a customer**

Hi,

For deploying to AWS ECS, we are using `/modules/ecs-service-with-alb?ref=v0.10.1` with the container definition attached below. This works for our own application because our app runs in a single docker container. However, we are experimenting with a 3rd party application that runs with docker-compose (4-5 containers). How can we deploy such an application stack to AWS ECS? Do we need a different module? Or if we can use different task definitions with the same module?

Thanks.

```
[
  {
    "name": "${container_name}",
    "image": "${image}:${version}",
    "cpu": ${cpu},
    "memory": ${memory},
    "essential": true,
    "portMappings": ${port_mappings},
    "environment": ${env_vars},
    "logConfiguration": {
      "logDriver": "syslog",
      "options": {
        "tag": "${container_name} ({{.ID}})"
      }
    }
  }
]
```

**Comment by gruntwork-support** [comment, marked as answer]
**From a grunt**

So, rather than multiple task definitions, the way to do this is by defining side cars in the container definition. How are you generating the container definition list? Maybe you can make it so that it supports multiple containers.

**Reply by gruntwork-support** [reply]
**From a customer**

Thank you for the reply. For our own single-container application, we basically set the `ecs_task_container_definitions` variable value to the container definition file. Our ECS deployment script specifies the parameter values in the definition. For this 3rd party app, we have the `docker-compose.yml`. Do you have a sample definition that is translated from a docker-compose.yml? Thanks.

**Reply by gruntwork-support** [reply]
**From a grunt**

For this, what you can do is add more container definitions to the template you've posted above. See how it is a list, lines 1 and 17 are `[` and `]`? You can add more within that list.

Each object in that list will be a container run as a side car in the same ECS service.

Wherever you're calling `data "template_file" "ecs_task_container_definitions"`, probably within your `ecs-with-alb-service/main.tf`, you can pass in the different input vars you need.

**Reply by gruntwork-support** [reply]
**From a customer**

person thank you very much for your reply. I'm not sure if specifying multiple tasks in a single definition would solve my problem. the multiple tasks seem "independent" services to me (maybe I missed something), but the docker-compose specifies a stack in which the containers are coordinated through their own network. ecs-cli compose may work, but we've never use the CLI interface so I have no experience with it. I'll have to study it. It'll be nice if gruntworks can offer some terraform modules for this purpose. Thanks.

**Reply by gruntwork-support** [reply]
**From a grunt**

I see. So, you should be able to create a list of container definitions as I mentioned before, where you list them in that top level `[ ]` . Everything in there will be deployed to the same host, so they're all services running together on the same "machine" which means they can talk to each other. So all the things you have defined under "services" will be separate side-car containers on the same host. Your overall cluster will consist of several of those hosts, all containing those services.

**Comment by gruntwork-support** [comment]
**From a grunt**

Hm, can you actually share this docker-compose file that specifies the stack/network concept? It might help me understand what I'm missing.

I did a very rudimentary digging on the interwebs for this, and found something native to AWS: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html

It looks like `ecs-cli` compose can do this conversion. Does this fit your bill? If we need to automate something to make this easier for you, please let us know.

**Reply by gruntwork-support** [reply]
**From a customer**

person here is the yml file. The services in docker compose reference each other by their own network names in their own networks. Maybe similar configurations can be done in a ECS task definition, but I don't know how (that's the  reason for my request for a sample  docker-compose to task definition translation). If you can show me how to map the yml file to a task definition, I'd definitely give it a try. Appreciate your help.

```
version: '2'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ./docker.env
    environment:
      - SERVICE_TYPE=MAIN_BACKEND
      - DB_CONNECTOR_HOST=http://db-connector
      - DB_CONNECTOR_PORT=3002
      - DB_SSH_CONNECTOR_HOST=http://db-ssh-connector
      - DB_SSH_CONNECTOR_PORT=3002
    networks:
      - frontend-network
      - backend-network
      - db-connector-network
      - db-ssh-connector-network
    depends_on:
      - postgres
      - db-connector
      - db-ssh-connector
    command: bash -c "./docker_scripts/wait-for-it.sh postgres:5432; ./docker_scripts/start_api.sh"
    links:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - ./keys:/root/.ssh
      - ssh:/retool_backend/autogen_ssh_keys

  jobs-runner:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ./docker.env
    environment:
      - SERVICE_TYPE=JOBS_RUNNER
    networks:
      - backend-network
    depends_on:
      - postgres
    command: bash -c "chmod -R +x ./docker_scripts; sync; ./docker_scripts/wait-for-it.sh postgres:5432; ./docker_scripts/start_api.sh"
    links:
      - postgres

  db-connector:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "./retool_backend"
    env_file: ./docker.env
    environment:
      - SERVICE_TYPE=DB_CONNECTOR_SERVICE
    networks:
      - db-connector-network
    restart: on-failure

  db-ssh-connector:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "./docker_scripts/generate_key_pair.sh; ./retool_backend"
    env_file: ./docker.env
    environment:
      - SERVICE_TYPE=DB_SSH_CONNECTOR_SERVICE
    networks:
      - db-ssh-connector-network
    volumes:
      - ssh:/retool_backend/autogen_ssh_keys
      - ./keys:/retool_backend/keys
    restart: on-failure

  # Retool's storage database. See these docs to migrate to an externally hosted database: https://docs.retool.com/docs/configuring-retools-storage-database
  postgres:
    image: 'postgres:9.6.5'
    env_file: docker.env
    networks:
      - backend-network
      - db-connector-network
    volumes:
      - data:/var/lib/postgresql/data

  # Not required, but leave this container to use nginx for handling the frontend & SSL certification
  https-portal:
    image: tryretool/https-portal:latest
    ports:
      - '80:80'
      - '443:443'
    links:
      - api
    restart: always
    env_file: ./docker.env
    environment:
      STAGE: 'local' # <- Change 'local' to 'production' to use a LetsEncrypt signed SSL cert
    networks:
      - frontend-network
networks:
  frontend-network:
  backend-network:
  db-connector-network:
  db-ssh-connector-network:

volumes:
  ssh:
  data:
  user-data:
```
