### DISCUSSION TITLE
Missing Kubernetes Service with k8s-service helm chart?

### DISCUSSION THREAD

**Discussion by yorinasub17** [gruntwork-io/knowledge-base#354] [Help]
Hey everyone, I'm having some issues when using the Helm Chart at https://github.com/gruntwork-io/helm-kubernetes-services to deploy a service alongside my deployment. I have enabled the service map in the `values.yaml` file, and confirmed that the result generates a proper service resource when I run  `helm template -f path/to/values.yaml helm-chart --debug`. However, when I run `terragrunt apply`, the deployment is created correctly, but the desired service does not. Any ideas as to why this could be happening?

Here's my current code for reference:

```
# service field in values.yaml:
service:
  enabled: true
  labels:
    app: application-name
  type: NodePort
  ports:
    app:
      port: 3181
      nodePort: 3181
      protocol: TCP
      targetPort: 3181
  selector:
    app: application-name 
```

resulting service yaml from helm template command:

```
# Source: k8s-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-application-name
  labels:
    # These labels are required by helm. You can read more about required labels in the chart best practices guide:
    # https://docs.helm.sh/chart_best_practices/#standard-labels
    app.kubernetes.io/name: application-name
    helm.sh/chart: k8s-service-0.0.1-replace
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app: application-name
spec:
  type: NodePort
  ports:
    - name: app
      nodePort: 3181
      port: 3181
      protocol: TCP
      targetPort: 3181
  selector:
    app.kubernetes.io/name: application-name
    app.kubernetes.io/instance: release-name
    app: application-name
```

I can confirm that the deployment is running correctly when I run `kubectl get pods` but I can't find the service when I run `kubectl get services`.
