### DISCUSSION TITLE
Terragrunt Appending Command to File Path

### DISCUSSION THREAD

**Discussion by davidtram0610** [gruntwork-io/knowledge-base#705] [Help]
After updating to awscli==1.24.10, botocore==1.26.10, boto3== 1.23.10, when my pipeline execute this command:
`terragrunt run-all plan --terragrunt-non-interactive`
The pipeline encounters this error:
> 2023/05/03 11:07:14 Error downloading: stat /__w/12/s/Terraform/infra-live/dev/run-all: no such file or directory

Here is how my folder structure looks like:
Terraform/
├── infra-live/
│   ├── dev/
│   │   ├── kms/
│   │   │   ├── variables.tf
│   │   │   ├── main.tf
│   │   │   ├── outputs.tf
│   │   │   ├── terragrunt.hcl
│   └── env.hcl

I also try to run `terragrunt validate --terragrunt-non-interactive`, the error is

> 2023/05/03 11:38:30 Error downloading: stat /__w/22/s/Terraform/infra-live/dev/validate: no such file or directory

My observation is that somehow, terragrunt appends the commands to the file path which makes the pipeline unable to pickup the infra-structure code. 

Have anyone experienced this issue or have any ideas what is going under the hood with terragrunt to cause this behavior?

---

<ins datetime="2023-05-03T18:39:39Z">
  <p><a href="https://support.gruntwork.io/hc/requests/110139">Tracked in ticket #110139</a></p>
</ins>

**Comment by denis256** [comment]
Hi,
which version of Terragrunt is used? it is installed from Github releases or used a wrapper like tgenv?
Can be shared sample repository where this issue happens and execution output with `--terragrunt-log-level debug`  ?

**Reply by davidtram0610** [reply]
Hello Denis,
My Terragrunt version is 0.45.0. It is included in the container image built by our company's in-house DevOps team (Ubuntu2004). 
Since this is my company's work, I cannot share with you the code, but in our pipeline, we have something like this:

terraform-deployment.yml:
```yaml
trigger: none

resources:
  pipelines:
  - pipeline: 'lambda_build_pipeline'  # identifier for the pipeline resource
    source: 'Eclipse Image Sync Lambda Build' # source pipeline definition name

variables:
  - name: lambda_build_artifact
    value: 'dotnet_lambda_$(resources.pipeline.lambda_build_pipeline.runName).zip'

parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: dev
    values:
    - dev
    - uat
    - prod
    - dr-prod

stages:
  - stage: DevDeployment
    displayName: Dev Deployment
    condition: eq('${{ parameters.environmentName}}', 'dev')

    jobs:
      - deployment: Dev_Deployment
        displayName: DEV Deployment
        pool:
          name: VMSS-Linux-DEV
        container:
          image: ssppaps1arpscr1.azurecr.io/ubuntu2004-build3-agent
          endpoint: DevOps-ACR-PROD
        workspace:
          clean: all
        environment: 'dev'
        variables:
          - group: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: terraform-stage-deployment.yml
                  parameters:
                    environmentName: 'dev'
                    lambdaZip: $(lambda_build_artifact)
```

terraform-stage-deployment.yml
```yaml
parameters:
  - name: environmentName
    displayName: 'Choose Environment for Terraform Deployment'
    type: string
    default: 'dev'
    values:
      - dev
      - uat
      - prod
      - dr-prod
steps:
  - task: terraformInstaller@0
    inputs:
      terraformVersion: 1.4.6
    displayName: Install Terraform
  - task: Bash@3
    name: RunTerragruntPlan
    displayName: Run Terragrunt Plan-All
    inputs:
      failOnStderr: false
      targetType: inline
      workingDirectory: $(Build.SourcesDirectory)/Terraform/infra-live/${{ parameters.environmentName }}
      script: |
       set -exo pipefail
       terragrunt run-all plan  --terragrunt-non-interactive
```
Python version is 3.8
awscli version is 1.27.126
botocore version is 1.29.126
boto3 version is 1.26.126

When I add `--terragrunt-log-level debug`, it just errors out here: `Error downloading: stat /__w/22/s/Terraform/infra-live/dev/validate: no such file or directory`
