### DISCUSSION TITLE
How to set up pod affinity in EKS - deployed as EC2 cluster

### DISCUSSION THREAD

**Discussion by pras111gw** [gruntwork-io/knowledge-base#712] [How do I]
If your EKS deployment uses fargate: please see https://github.com/orgs/gruntwork-io/discussions/708

In EKS (deployed on EC2 cluster), you can control pod placement using pod affinity rules. Pod affinity allows you to define constraints on how pods should be scheduled on nodes based on labels and topology constraints. This feature helps you influence the placement of pods to achieve better performance, fault tolerance, and resource utilization in your cluster.

Here's how you can control pod affinity in EKS:

**Define Labels:** First, make sure you have appropriate labels set on your nodes and pods. Labels are key-value pairs that identify resources. For example, you might label nodes with attributes like environment: production or availability-zone: us-west-1a.

**Create Pod Affinity Rule:** To control pod affinity, you need to create a Pod Affinity Rule manifest file or use Kubernetes command-line tools such as kubectl to define the rule. The Pod Affinity Rule specifies the conditions under which pods should be scheduled close to or far away from each other.

An example of a Pod Affinity Rule manifest file:

```yaml
apiVersion: scheduling.k8s.io/v1
kind: PodAffinity
metadata:
  name: my-pod-affinity
spec:
  requiredDuringSchedulingIgnoredDuringExecution:
  - labelSelector:
      matchExpressions:
      - key: app
        operator: In
        values:
        - my-app
    topologyKey: kubernetes.io/hostname
```

In the example above, pods with the label app=my-app are required to be scheduled on nodes that share the same hostname. Modify the rule to match your specific requirements.

Apply the Rule: Use the kubectl apply command to apply the Pod Affinity Rule to your EKS cluster:

```bash
kubectl apply -f pod-affinity-rule.yaml
```
Replace pod-affinity-rule.yaml with the path to your rule manifest file.

Verify the Placement: After applying the Pod Affinity Rule, Kubernetes will automatically start scheduling pods based on the defined constraints. You can verify the placement by inspecting the pod's node using the kubectl get pods -o wide command. The output will display the assigned node for each pod.

By using pod affinity rules, you have fine-grained control over pod scheduling in your EKS cluster, allowing you to optimize resource allocation and improve performance based on your application's requirements.

---

<ins datetime="2023-05-16T01:00:10Z">
  <p><a href="https://support.gruntwork.io/hc/requests/110170">Tracked in ticket #110170</a></p>
</ins>
